#!/usr/bin/env python3
"""Topic Onboarding — Workflow for onboarding new analytical topics.

Given a topic specification, builds the analyst configuration:
- Themes (the analytical lens dimensions)
- Source inventory (candidate sources, prioritized)
- Calibration tracking baseline
- Entity skeleton (key entities to track)
- Routing rules (any topic-specific escalation)

Saves to config/topics/<topic-slug>/

Usage:
    python3 analyst/topic_onboarding.py --topic "Brazil fiscal policy through end of 2027"
    python3 analyst/topic_onboarding.py --spec path/to/topic-spec.yaml
"""
from __future__ import annotations

import json
import os
import re
import time
from dataclasses import dataclass, field, asdict
from pathlib import Path
from typing import Any, Optional


WORKSPACE = Path(__file__).resolve().parent.parent
TOPICS_DIR = WORKSPACE / "config" / "topics"
ACTIVE_ASSIGNMENTS = WORKSPACE / "config" / "active-assignments.yaml"


@dataclass
class TopicConfig:
    """Generated topic configuration."""
    slug: str
    name: str
    description: str
    themes: list[dict]
    sources: list[dict]
    entities: list[dict]
    calibration_baseline: dict
    routing_overrides: dict
    created_at: str = ""
    onboarding_cost_usd: float = 0.0

    def __post_init__(self):
        if not self.created_at:
            self.created_at = time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime())


def slugify(name: str) -> str:
    """Convert topic name to filesystem-safe slug."""
    s = name.lower().strip()
    s = re.sub(r'[^a-z0-9\s-]', '', s)
    s = re.sub(r'[\s-]+', '-', s)
    return s[:60].rstrip('-')


def _build_topic_yaml(slug: str, name: str, description: str, time_horizon: str = "") -> str:
    """Build topic.yaml content."""
    return f"""# Topic Configuration: {name}
# Generated by topic_onboarding.py

slug: {slug}
name: "{name}"
description: "{description}"
time_horizon: "{time_horizon}"
status: active
created: {time.strftime("%Y-%m-%d")}

# Scope definition for scope_check.py
primary_scope: "{name}"
scope_description: >
  Analysis of {description}.
  Adjacent topics with direct impact on this topic are in scope
  when the connection is made explicit. Tangential topics are out of scope.

# Adjacency vectors — topics that connect to this one
adjacency_vectors: []

# Blocklist — topics explicitly out of scope
blocklist: []

# In-scope keywords (fast-path for scope_check)
in_scope_keywords: []
"""


def _build_themes_yaml(themes: list[dict]) -> str:
    """Build themes.yaml content from theme list."""
    lines = ["# Theme Requirements for Topic"]
    lines.append("# Generated by topic_onboarding.py")
    lines.append("")
    lines.append("themes:")
    for theme in themes:
        lines.append(f"  - name: {theme.get('name', 'unnamed')}")
        lines.append(f"    description: \"{theme.get('description', '')}\"")
        lines.append(f"    priority: {theme.get('priority', 'medium')}")
        keywords = theme.get('keywords', [])
        if keywords:
            lines.append(f"    keywords: [{', '.join(keywords)}]")
        lines.append("")
    return "\n".join(lines)


def _build_sources_yaml(sources: list[dict]) -> str:
    """Build sources.yaml content from source list."""
    lines = ["# Source Inventory for Topic"]
    lines.append("# Generated by topic_onboarding.py")
    lines.append("")
    lines.append("sources:")
    for source in sources:
        lines.append(f"  - name: \"{source.get('name', '')}\"")
        lines.append(f"    url: \"{source.get('url', '')}\"")
        lines.append(f"    type: {source.get('type', 'web')}")
        lines.append(f"    reliability: {source.get('reliability', 'B')}")
        lines.append(f"    credibility: {source.get('credibility', '3')}")
        lines.append(f"    update_frequency: {source.get('update_frequency', 'daily')}")
        lines.append(f"    language: {source.get('language', 'en')}")
        lines.append("")
    return "\n".join(lines)


def _build_entities_yaml(entities: list[dict]) -> str:
    """Build entities.yaml content from entity list."""
    lines = ["# Entity Tracking for Topic"]
    lines.append("# Generated by topic_onboarding.py")
    lines.append("")
    lines.append("entities:")
    for entity in entities:
        lines.append(f"  - name: \"{entity.get('name', '')}\"")
        lines.append(f"    type: {entity.get('type', 'organization')}")
        lines.append(f"    importance: {entity.get('importance', 'medium')}")
        lines.append(f"    aliases: [{', '.join(entity.get('aliases', []))}]")
        lines.append("")
    return "\n".join(lines)


def _build_calibration_json(topic_name: str) -> dict:
    """Build initial calibration tracking baseline."""
    return {
        "topic": topic_name,
        "created": time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime()),
        "judgments": [],
        "calibration_bands": {
            "almost_certain": {"range": [93, 99], "count": 0, "correct": 0},
            "highly_likely": {"range": [80, 92], "count": 0, "correct": 0},
            "likely": {"range": [63, 79], "count": 0, "correct": 0},
            "chances_about_even": {"range": [40, 62], "count": 0, "correct": 0},
            "unlikely": {"range": [21, 39], "count": 0, "correct": 0},
            "highly_unlikely": {"range": [8, 20], "count": 0, "correct": 0},
            "remote": {"range": [2, 7], "count": 0, "correct": 0},
            "negligible": {"range": [0, 1], "count": 0, "correct": 0},
        },
        "brier_scores": [],
        "postdiction_queue": [],
    }


def _build_routing_overrides_yaml() -> str:
    """Build routing-overrides.yaml (empty by default)."""
    return """# Topic-Specific Routing Overrides
# Leave empty to use default llm_gate routing.
# Add overrides here to customize model selection for this topic.

# Example:
# subscriber_brief:
#   escalate_if_any:
#     - audience:family_office
#   budget_cap: 10.00
"""


def _build_branding_yaml(topic_name: str) -> str:
    """Build branding.yaml for topic-specific presentation."""
    return f"""# Branding for {topic_name}
# Used by render_pdf.py and render_audio.py

brand_name: "Trevor Intelligence"
topic_label: "{topic_name}"
color_primary: "#1a1a2e"
color_accent: "#e94560"
logo_path: ""
footer_text: "Trevor Intelligence | Calibrated Analysis"
audio_voice_id: "21m00Tcm4TlvDq8ikWAM"
"""


def onboard_topic(
    name: str,
    description: str = "",
    time_horizon: str = "",
    themes: Optional[list[dict]] = None,
    sources: Optional[list[dict]] = None,
    entities: Optional[list[dict]] = None,
) -> TopicConfig:
    """
    Onboard a new analytical topic.

    Creates the full config/topics/<slug>/ directory with all configuration
    files needed for Trevor to begin analytical work on this topic.

    In production, the strategic phase (theme identification, scenario space)
    would call Opus 4.7, and the tactical phase (source inventory, entity list)
    would call V4 Pro. This function creates the file structure; the LLM calls
    are orchestrated by the calling workflow.

    Args:
        name: Human-readable topic name
        description: Detailed topic description
        time_horizon: e.g., "through end of 2027"
        themes: Pre-defined themes (or empty for LLM generation)
        sources: Pre-defined sources (or empty for LLM discovery)
        entities: Pre-defined entities (or empty for LLM identification)

    Returns:
        TopicConfig with all generated configuration
    """
    if not description:
        description = name

    slug = slugify(name)
    topic_dir = TOPICS_DIR / slug
    topic_dir.mkdir(parents=True, exist_ok=True)

    # Default empty structures if not provided
    if themes is None:
        themes = []
    if sources is None:
        sources = []
    if entities is None:
        entities = []

    # Write all config files
    (topic_dir / "topic.yaml").write_text(_build_topic_yaml(slug, name, description, time_horizon))
    (topic_dir / "themes.yaml").write_text(_build_themes_yaml(themes))
    (topic_dir / "sources.yaml").write_text(_build_sources_yaml(sources))
    (topic_dir / "entities.yaml").write_text(_build_entities_yaml(entities))
    (topic_dir / "calibration.json").write_text(
        json.dumps(_build_calibration_json(name), indent=2)
    )
    (topic_dir / "routing-overrides.yaml").write_text(_build_routing_overrides_yaml())
    (topic_dir / "branding.yaml").write_text(_build_branding_yaml(name))

    config = TopicConfig(
        slug=slug,
        name=name,
        description=description,
        themes=themes,
        sources=sources,
        entities=entities,
        calibration_baseline=_build_calibration_json(name),
        routing_overrides={},
    )

    return config


def list_topics() -> list[str]:
    """List all onboarded topic slugs."""
    if not TOPICS_DIR.exists():
        return []
    return sorted([
        d.name for d in TOPICS_DIR.iterdir()
        if d.is_dir() and (d / "topic.yaml").exists()
    ])


def get_topic_config(slug: str) -> Optional[dict]:
    """Load a topic's configuration."""
    topic_dir = TOPICS_DIR / slug
    if not topic_dir.exists():
        return None
    config = {"slug": slug}
    for fname in ["topic.yaml", "themes.yaml", "sources.yaml", "entities.yaml"]:
        fpath = topic_dir / fname
        if fpath.exists():
            config[fname.replace(".yaml", "")] = fpath.read_text()
    cal_path = topic_dir / "calibration.json"
    if cal_path.exists():
        config["calibration"] = json.loads(cal_path.read_text())
    return config


# ── CLI ──────────────────────────────────────────────────────────────────────
if __name__ == "__main__":
    import sys

    if len(sys.argv) < 3 or sys.argv[1] != "--topic":
        print("Usage: python3 analyst/topic_onboarding.py --topic 'Topic name here'")
        print("\nExisting topics:")
        for t in list_topics():
            print(f"  - {t}")
        sys.exit(1)

    topic_name = sys.argv[2]
    desc = sys.argv[3] if len(sys.argv) > 3 else topic_name
    horizon = sys.argv[4] if len(sys.argv) > 4 else ""

    config = onboard_topic(topic_name, desc, horizon)
    topic_dir = TOPICS_DIR / config.slug
    print(f"Topic onboarded: {config.name}")
    print(f"Slug: {config.slug}")
    print(f"Directory: {topic_dir}")
    print(f"Files created: {', '.join(f.name for f in topic_dir.iterdir())}")
    print("\nNext steps:")
    print("1. Run strategic phase (Opus 4.7) to populate themes")
    print("2. Run tactical phase (V4 Pro) to populate sources and entities")
    print("3. Run operational phase (V4 Flash) to wire collectors")


# Backward-compatible alias
TopicOnboarding = onboard_topic
