#!/usr/bin/env python3
"""
Generate a new skill scaffold from a capability-gap description.

Usage:
    python3 skills/skill-generator/scripts/generate_skill.py \\
        --gap "Cannot OCR Spanish-language PDFs from SEDENA briefings" \\
        --name spanish-pdf-ocr

The script:
  1. Creates skills/<name>/{SKILL.md, scripts/<verb>.py}
  2. Refuses if skills/<name>/ already exists.
  3. Appends a generation record to
     brain/memory/semantic/skill-generation-log.jsonl
  4. Updates skills/registry.json if present.

The generated script is a stub — main() raises NotImplementedError. The
intent is to make the gap reservable, not to ship unverified code into
the autonomous pipeline.
"""
from __future__ import annotations

import argparse
import datetime as dt
import json
import pathlib
import re
import sys


REPO_ROOT = pathlib.Path(__file__).resolve().parent.parent.parent.parent
SKILLS_DIR = REPO_ROOT / "skills"
LOG_PATH = REPO_ROOT / "brain" / "memory" / "semantic" / "skill-generation-log.jsonl"
REGISTRY_PATH = SKILLS_DIR / "registry.json"


def log(msg: str) -> None:
    ts = dt.datetime.now(dt.timezone.utc).strftime("%H:%M:%S")
    print(f"[skill-gen {ts}] {msg}", file=sys.stderr, flush=True)


def slugify(text: str) -> str:
    text = text.lower().strip()
    text = re.sub(r"[^a-z0-9\s-]", "", text)
    text = re.sub(r"\s+", "-", text)
    text = re.sub(r"-+", "-", text)
    return text.strip("-")[:48] or "untitled-skill"


def render_skill_md(name: str, gap: str, verb: str) -> str:
    return f"""# {name}

**Status:** drafted (stub — not yet implemented)
**Owner:** trevor (skill-generator loop)
**Added:** {dt.date.today().isoformat()}

## Purpose

Generated to close a capability gap identified during weekly
meta-review / framework reflection:

> {gap}

## When to invoke

TBD — fill in once the implementation is in place.

## Inputs

TBD.

## Outputs

TBD.

## Status

This is a stub. `scripts/{verb}.py` raises NotImplementedError. Either
fill it in manually or invoke a follow-up generation session to flesh
out the body once the design is settled.

A row was added to `brain/memory/semantic/skill-generation-log.jsonl`
so the weekly review can see whether this stub was completed.
"""


def render_script(name: str, verb: str, gap: str) -> str:
    return f'''#!/usr/bin/env python3
"""
{name} — stub generated by skill-generator.

Gap this addresses:
    {gap}

TODO: replace NotImplementedError in main() with the real implementation.
"""
from __future__ import annotations

import argparse
import datetime as dt
import sys


def log(msg: str) -> None:
    ts = dt.datetime.now(dt.timezone.utc).strftime("%H:%M:%S")
    print(f"[{name} {{ts}}] {{msg}}", file=sys.stderr, flush=True)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--dry-run", action="store_true")
    parser.parse_args()

    raise NotImplementedError(
        "{name} is a stub generated by skill-generator. "
        "Fill in main() before invoking from the autonomous pipeline."
    )


if __name__ == "__main__":
    sys.exit(main())
'''


def append_log(name: str, gap: str, path: pathlib.Path) -> None:
    LOG_PATH.parent.mkdir(parents=True, exist_ok=True)
    entry = {
        "ts": dt.datetime.now(dt.timezone.utc).isoformat() + "Z",
        "name": name,
        "gap": gap,
        "path": str(path.relative_to(REPO_ROOT)),
        "status": "stub",
    }
    with LOG_PATH.open("a") as fh:
        fh.write(json.dumps(entry) + "\n")


def update_registry(name: str, gap: str) -> None:
    if not REGISTRY_PATH.exists():
        return
    try:
        reg = json.loads(REGISTRY_PATH.read_text())
    except json.JSONDecodeError:
        log("registry.json malformed — leaving alone")
        return
    if isinstance(reg, dict) and "skills" in reg and isinstance(reg["skills"], list):
        reg["skills"].append({
            "name": name,
            "status": "stub",
            "purpose": gap[:140],
            "added": dt.date.today().isoformat(),
            "source": "skill-generator",
        })
        REGISTRY_PATH.write_text(json.dumps(reg, indent=2))
        log(f"appended {name} to registry.json")


def main() -> int:
    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument("--gap", required=True,
                   help="One-sentence description of the capability gap")
    p.add_argument("--name", default="",
                   help="Skill name (kebab-case). Default: derived from gap.")
    p.add_argument("--verb", default="run",
                   help="Stub script verb (default: run → scripts/run.py)")
    args = p.parse_args()

    name = args.name.strip() or slugify(args.gap)
    name = slugify(name)
    skill_dir = SKILLS_DIR / name
    if skill_dir.exists():
        log(f"refusing — skills/{name}/ already exists")
        return 2

    scripts_dir = skill_dir / "scripts"
    scripts_dir.mkdir(parents=True)
    (skill_dir / "SKILL.md").write_text(render_skill_md(name, args.gap, args.verb))
    script_path = scripts_dir / f"{args.verb}.py"
    script_path.write_text(render_script(name, args.verb, args.gap))
    script_path.chmod(0o755)

    append_log(name, args.gap, skill_dir)
    update_registry(name, args.gap)

    log(f"scaffold created at skills/{name}/")
    print(str(skill_dir.relative_to(REPO_ROOT)))
    return 0


if __name__ == "__main__":
    sys.exit(main())
