# GATE_EXEMPT: Audio generation script — calls ElevenLabs TTS API directly. Not an analytical model call. Generated by brazil-flagship sub-agent.
#!/usr/bin/env python3
"""Generate audio companion for Brazil Fiscal Brief using ElevenLabs TTS - premade voice."""
import os
import sys
import requests

API_KEY = os.environ.get("ELEVENLABS_API_KEY")
if not API_KEY:
    print("Skipping: no API key")
    sys.exit(0)

OUTPUT_DIR = "/home/ubuntu/.openclaw/workspace/memory/2026-05-v2-validation/brazil-flagship"

script = """Trevor Intelligence presents: Brazil Fiscal Trajectory, H2 2026 plus 2027 Outlook. A multi-scenario assessment for family offices with emerging market exposure.

Executive Summary. Brazil enters the second half of 2026 at a fiscal inflection point. The probability-weighted central case, assessed at 45 percent confidence, points to a gradual, incomplete, and politically contingent fiscal consolidation. This path is sufficient to avoid crisis but insufficient to restore investment-grade credibility. The risk asymmetry is skewed to the downside, with 40 percent weight on adverse scenarios versus 15 percent upside.

The single most important number to watch is the primary balance. The government targets a surplus of 0.25 percent of GDP for 2026. We judge with moderate confidence that the target will be missed by 0.3 to 0.6 percentage points, producing an effective deficit of 0.4 to 0.6 percent of GDP. Brazil's gross public debt is projected to reach 96.5 percent of GDP in 2026, rising to approximately 99 percent by end 2027.

Four Scenarios. The base case, with 45 percent probability, sees the Selic decline from 14.5 percent to 11.25 percent by end 2027. The dollar-real trades between 4.55 and 5.45, with central tendency around 5.07. Growth remains below potential at 1.7 percent in 2026 and 2 percent in 2027. The upside scenario, at 15 percent, envisions a reform breakthrough, the Selic falling below 10 percent, and growth accelerating to 2.5 to 3 percent. The downside scenario, at 30 percent, sees fiscal drift with debt exceeding 100 percent of GDP, the Selic stuck above 12.5 percent, and growth below 1.5 percent. The tail scenario, at 10 percent probability, is a full fiscal crisis, contested election, or external oil shock.

The 2026 election on October 4th is the critical branching point. We assign 55 percent probability to Lula's re-election and 45 percent to an opposition victory. Current Polymarket probabilities show Lula at 42 percent, Flavio Bolsonaro at 37 percent, and Tarcisio de Freitas at 15 percent.

Sectoral recommendations. Overweight Petrobras as the single best risk-adjusted position in Brazilian equities, supported by oil price tailwinds from the Iran conflict and privatization optionality. Underweight consumer discretionary, facing earnings contraction of 5 to 10 percent in 2026 driven by high household debt and decelerating wages.

Tactical positioning for H2 2026. One: reduce Brazilian real duration to under two years. Two: maintain the carry trade with election hedges. Three: overweight Petrobras. Four: underweight consumer discretionary until second quarter 2027.

This concludes the Brazil Fiscal Trajectory executive audio summary. Full details including all 34 calibrated judgments and the complete watch calendar are available in the written report."""

url = "https://api.elevenlabs.io/v1/text-to-speech/EXAVITQu4vr4xnSDxMaL"  # Sarah - premade voice
headers = {
    "Accept": "audio/mpeg",
    "Content-Type": "application/json",
    "xi-api-key": API_KEY,
}
data = {
    "text": script,
    "model_id": "eleven_turbo_v2_5",
    "voice_settings": {
        "stability": 0.40,
        "similarity_boost": 0.70,
    }
}

print(f"Generating audio ({len(script.split())} words)...")
resp = requests.post(url, json=data, headers=headers, timeout=30)
if resp.status_code == 200:
    out = os.path.join(OUTPUT_DIR, "brazil-fiscal-h2-2026-outlook.mp3")
    with open(out, "wb") as f:
        f.write(resp.content)
    print(f"✓ Audio companion generated: {out} ({len(resp.content)/1024:.0f} KB)")
else:
    print(f"API error: {resp.status_code} - {resp.text[:300]}")
