#!/usr/bin/env python3
"""Daily Intel Brief orchestrator.

Runs Steps 0-6 from skills/daily-intel-brief/SKILL.md. Spawns the three
worker scripts (collect.py, analyze.py, build_visuals.py), runs the PDF
assembler (build_pdf.py), and optionally hands the final product to
agentmail for delivery.

Designed to be invoked from cron, but works fine as a one-shot.

Usage:

    python3 skills/daily-intel-brief/scripts/orchestrate.py
    python3 skills/daily-intel-brief/scripts/orchestrate.py --dry-run --use-mock-incidents
    python3 skills/daily-intel-brief/scripts/orchestrate.py --working-dir ~/trevor-briefings/2026-05-01
    python3 skills/daily-intel-brief/scripts/orchestrate.py --no-deliver

Exits non-zero on any failure that should block tomorrow's run (e.g. a
missing required env var). Calibration smells are reported to stderr
but do not block the run.
"""
from __future__ import annotations

import argparse
import datetime as dt
import json
import os
import pathlib
import subprocess
import sys
import threading
import time
from typing import Optional

REPO_ROOT = pathlib.Path(__file__).resolve().parents[3]
SKILL_DIR = pathlib.Path(__file__).resolve().parent.parent
SCRIPTS = SKILL_DIR / "scripts"




def log(msg: str) -> None:
    ts = dt.datetime.utcnow().strftime("%Y-%m-%dT%H:%M:%SZ")
    print(f"[{ts}] {msg}", flush=True)


def fail(msg: str, code: int = 2) -> "None":
    log(f"FATAL: {msg}")
    sys.exit(code)


REQUIRED_ENV = ["OPENROUTER_API_KEY"]
OPTIONAL_ENV = ["DEEPSEEK_API_KEY", "MAPBOX_TOKEN", "CHARTGEN_API_KEY", "AGENTMAIL_API_KEY"]


def env_check(strict: bool = True) -> None:
    missing = [k for k in REQUIRED_ENV if not os.environ.get(k)]
    if missing and strict:
        fail(
            "missing required env vars: "
            + ", ".join(missing)
            + ". Set them in ~/.openclaw/secrets/ and source via cron."
        )
    for k in OPTIONAL_ENV:
        if not os.environ.get(k):
            log(f"NOTE: optional env var {k} not set; falling back per skill spec.")


def working_dir(date_utc: str, override: Optional[str]) -> pathlib.Path:
    if override:
        wd = pathlib.Path(override).expanduser().resolve()
    else:
        wd = pathlib.Path("~/trevor-briefings").expanduser().resolve() / date_utc
    for sub in ("raw", "analysis", "visuals", "final"):
        (wd / sub).mkdir(parents=True, exist_ok=True)
    return wd


def write_framing(wd: pathlib.Path, date_utc: str) -> None:
    framing = wd / "00-framing.md"
    if framing.exists():
        return
    framing.write_text(
        f"# Daily Brief — Framing — {date_utc}\n\n"
        "**Question:** Provide Trevor's principal with the most\n"
        "decision-relevant security and financial picture from the last\n"
        "24h, structured for ~5 minutes of read time.\n\n"
        "**Time horizon:** 7 days (per analyst calibration).\n\n"
        "**Out of scope:** ad-hoc single-region deep dives, single-incident\n"
        "analysis, non-security topics.\n\n"
        "**Confidence threshold:** calibrated bands per Sherman Kent;\n"
        "single-source key judgments capped at 'likely' (70%).\n\n"
        f"*Generated by orchestrator at {dt.datetime.utcnow().isoformat()}Z.*\n"
    )


def run_step(name: str, cmd: list[str], wd: pathlib.Path) -> int:
    log(f"START {name}: {' '.join(cmd)}")
    t0 = time.monotonic()
    try:
        rc = subprocess.call(cmd, cwd=str(REPO_ROOT))
    except FileNotFoundError as exc:
        log(f"END   {name}: rc=127 ({exc})")
        return 127
    log(f"END   {name}: rc={rc} ({time.monotonic()-t0:.1f}s)")
    return rc


def run_parallel(
    name_a: str, cmd_a: list[str],
    name_b: str, cmd_b: list[str],
    wd: pathlib.Path,
) -> tuple[int, int]:
    """Run two steps in parallel threads (subprocesses). Return (rc_a, rc_b)."""
    results: dict[str, int] = {}

    def worker(name: str, cmd: list[str]) -> None:
        results[name] = run_step(name, cmd, wd)

    t_a = threading.Thread(target=worker, args=(name_a, cmd_a), daemon=True)
    t_b = threading.Thread(target=worker, args=(name_b, cmd_b), daemon=True)
    t_a.start(); t_b.start()
    t_a.join(); t_b.join()
    return results.get(name_a, 1), results.get(name_b, 1)


def calibration_smell_check(wd: pathlib.Path) -> list[str]:
    """Surface obvious calibration drift to stderr without blocking the run."""
    smells: list[str] = []
    pcts: list[int] = []
    for path in sorted((wd / "analysis").glob("*.json")):
        if path.name == "exec_summary.json":
            continue
        try:
            payload = json.loads(path.read_text())
        except Exception:
            continue
        for kj in payload.get("key_judgments", []) or []:
            p = kj.get("prediction_pct")
            if isinstance(p, (int, float)):
                pcts.append(int(p))
    if not pcts:
        return smells
    n_high = sum(1 for p in pcts if p >= 75)
    if len(pcts) >= 6 and n_high / len(pcts) > 0.7:
        smells.append(
            f"calibration smell: {n_high}/{len(pcts)} key judgments at "
            "'highly likely' or above. Spread your bands."
        )
    if len(set(pcts)) <= max(2, len(pcts) // 4):
        smells.append(
            f"calibration smell: only {len(set(pcts))} distinct prediction "
            f"values across {len(pcts)} judgments. Look for round-number bias."
        )
    return smells


def quality_gates(wd: pathlib.Path) -> list[str]:
    """Lightweight programmatic version of analyst/playbooks/quality-gates.md.

    Returns a list of failures. Empty list = ship it.
    """
    failures: list[str] = []
    analysis_dir = wd / "analysis"
    expected = {
        "europe.json", "asia.json", "middle_east.json",
        "north_america.json", "south_central_america.json",
        "global_finance.json", "exec_summary.json",
    }
    have = {p.name for p in analysis_dir.glob("*.json")}
    missing = sorted(expected - have)
    if missing:
        failures.append(f"Gate 0 — missing analysis files: {missing}")
        return failures  # bail; downstream gates are pointless

    # Gate 2: verbal anchor and numeric prediction agree
    bands = {
        "almost certain": (93, 99),
        "highly likely": (75, 85),
        "likely": (55, 70),
        "probable": (55, 70),
        "even chance": (45, 55),
        "unlikely": (25, 35),
        "highly unlikely": (10, 20),
        "almost no chance": (1, 5),
    }
    for region_file in sorted(analysis_dir.glob("*.json")):
        if region_file.name == "exec_summary.json":
            continue
        payload = json.loads(region_file.read_text())
        for kj in payload.get("key_judgments", []) or []:
            band = (kj.get("sherman_kent_band") or "").lower().strip()
            pct = kj.get("prediction_pct")
            if band not in bands:
                failures.append(
                    f"Gate 2 — {region_file.name}:{kj.get('id')} unknown band {band!r}"
                )
                continue
            lo, hi = bands[band]
            if not isinstance(pct, (int, float)) or not (lo <= pct <= hi):
                failures.append(
                    f"Gate 2 — {region_file.name}:{kj.get('id')} "
                    f"band {band!r} requires {lo}-{hi}; got {pct!r}"
                )
            if kj.get("single_source_basis") and isinstance(pct, (int, float)) and pct > 70:
                failures.append(
                    f"Gate 3 — {region_file.name}:{kj.get('id')} "
                    f"single-source KJ exceeds likely (70%): {pct}"
                )
            ind = kj.get("what_would_change_it") or []
            if not isinstance(ind, list) or len(ind) < 2:
                failures.append(
                    f"Gate 4 — {region_file.name}:{kj.get('id')} needs "
                    "both a softener and a tightener in what_would_change_it"
                )

    # Gate 5: a red-team note exists
    if not (analysis_dir / "red_team.md").exists():
        failures.append("Gate 5 — analysis/red_team.md is missing")

    return failures


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--working-dir", default=None, help="override working dir")
    parser.add_argument("--dry-run", action="store_true", help="skip delivery")
    parser.add_argument("--use-mock-incidents", action="store_true",
                        help="use scripts/mock_incidents.json instead of live collection")
    parser.add_argument("--no-deliver", action="store_true",
                        help="produce the PDF/DOCX but skip agentmail")
    parser.add_argument("--model", default="anthropic/claude-opus-4.7",
                        help="model for the analyst (default: Opus 4.7 via OpenRouter)")
    parser.add_argument("--provider", choices=["deepseek", "openrouter"], default="openrouter",
                        help="API provider (default: openrouter)")
    parser.add_argument("--strict-env", action="store_true", default=True,
                        help="fail at start if required env vars are missing")
    args = parser.parse_args()

    log(f"orchestrator starting (dry_run={args.dry_run}, model={args.model})")
    env_check(strict=args.strict_env and not args.dry_run)

    date_utc = dt.datetime.utcnow().strftime("%Y-%m-%d")
    wd = working_dir(date_utc, args.working_dir)
    log(f"working dir: {wd}")
    write_framing(wd, date_utc)

    # Step 0 — brain recall (best-effort)
    brain_script = REPO_ROOT / "brain" / "scripts" / "brain.py"
    if brain_script.exists():
        run_step("brain-recall",
                 ["python3", str(brain_script), "recall",
                  "yesterday's brief and overnight events"], wd)

    # Step 1 — collector
    collector_cmd = [
        "python3", str(SCRIPTS / "collect.py"),
        "--working-dir", str(wd),
        "--regions", str(SKILL_DIR / "references" / "regions.json"),
        "--sources", str(REPO_ROOT / "analyst" / "meta" / "sources.json"),
    ]
    if args.use_mock_incidents:
        collector_cmd.append("--mock")
    rc = run_step("collector", collector_cmd, wd)
    if rc != 0:
        fail(f"collector exited with rc={rc}", rc)

    # Steps 2 and 3 in parallel
    analyst_cmd = [
        "python3", str(SCRIPTS / "analyze.py"),
        "--working-dir", str(wd),
        "--prompts", str(SKILL_DIR / "references" / "deepseek-prompts.md"),
        "--regions", str(SKILL_DIR / "references" / "regions.json"),
        "--model", args.model,
        "--provider", args.provider,
    ]
    if args.dry_run:
        analyst_cmd.append("--mock")
    visuals_cmd = [
        "python3", str(SCRIPTS / "build_visuals.py"),
        "--working-dir", str(wd),
        "--regions", str(SKILL_DIR / "references" / "regions.json"),
    ]
    rc_a, rc_v = run_parallel("analyst", analyst_cmd, "visuals", visuals_cmd, wd)
    if rc_a != 0:
        fail(f"analyst exited with rc={rc_a}", rc_a)
    if rc_v != 0:
        log(f"WARN: visuals exited with rc={rc_v} — continuing without all figures")

    # Step 4 — quality gates
    failures = quality_gates(wd)
    if failures:
        log("Quality gate failures:")
        for f in failures:
            log("  - " + f)
        fail("Quality gates failed; see above. Fix and rerun.", 3)
    smells = calibration_smell_check(wd)
    for s in smells:
        log("CALIBRATION SMELL: " + s)

    # Step 5 — assemble
    pdf_path = wd / "final" / f"brief-{date_utc}.pdf"
    docx_path = wd / "final" / f"brief-{date_utc}.docx"
    rc = run_step("assemble", [
        "python3", str(SCRIPTS / "build_pdf.py"),
        "--working-dir", str(wd),
        "--out-pdf", str(pdf_path),
        "--out-docx", str(docx_path),
    ], wd)
    if rc != 0:
        fail(f"assembler exited with rc={rc}", rc)

    # Step 6 — archive + deliver
    memory_dir = REPO_ROOT / "memory"
    memory_dir.mkdir(exist_ok=True)
    memory_file = memory_dir / f"{date_utc}.md"
    exec_summary_path = wd / "analysis" / "exec_summary.json"
    if exec_summary_path.exists():
        exec_summary = json.loads(exec_summary_path.read_text())
        with memory_file.open("a") as fh:
            fh.write(f"\n## Daily brief — {date_utc}\n\n")
            fh.write(f"BLUF: {exec_summary.get('bluf')}\n\n")
            for kj in exec_summary.get("five_judgments", []):
                fh.write(
                    f"- [{kj.get('drawn_from_region')}] "
                    f"{kj.get('statement')} "
                    f"({kj.get('sherman_kent_band')}; "
                    f"{kj.get('prediction_pct')}% / 7d)\n"
                )

    if brain_script.exists():
        run_step("brain-reindex", ["python3", str(brain_script), "reindex"], wd)

    if args.no_deliver or args.dry_run:
        log(f"delivery skipped; product at {pdf_path}")
        return 0

    if os.environ.get("AGENTMAIL_API_KEY"):
        agentmail_script = REPO_ROOT / "skills" / "agentmail" / "scripts" / "send_email.py"
        if agentmail_script.exists():
            rc = run_step("agentmail-deliver", [
                "python3", str(agentmail_script),
                "--to-config", "trevor.principal_email",
                "--subject", f"TREVOR Daily Brief — {date_utc}",
                "--attachment", str(pdf_path),
            ], wd)
            if rc != 0:
                log(f"WARN: agentmail rc={rc}; product at {pdf_path}")
        else:
            log(f"agentmail script not found; product at {pdf_path}")
    else:
        log(f"AGENTMAIL_API_KEY not set; product at {pdf_path}")

    return 0


if __name__ == "__main__":
    sys.exit(main())
