#!/usr/bin/env python3
"""Publish the daily OSINT brief to Buttondown newsletter.

Usage:
    python3 scripts/buttondown-publish.py                    # publish today's brief
    python3 scripts/buttondown-publish.py --file tasks/news_analysis.md
    python3 scripts/buttondown-publish.py --dry-run           # preview only

Requires:
    BUTTONDOWN_API_KEY env var (set in openclaw.json or .env)
"""
from __future__ import annotations

import json
import os
import sys
from datetime import datetime, timezone
from pathlib import Path
from urllib.request import Request, urlopen
from urllib.error import URLError

WORKSPACE = Path("/home/ubuntu/.openclaw/workspace")
API_URL = "https://api.buttondown.com/v1/emails"
NEWSLETTER_ID = "news_3fze7q360q9kmrjsp8fvp6rqmr"

# ── Parse args ──────────────────────────────────────────────────────

dry_run = "--dry-run" in sys.argv
brief_path = None
for i, a in enumerate(sys.argv):
    if a == "--file" and i + 1 < len(sys.argv):
        brief_path = Path(sys.argv[i + 1])

if not brief_path:
    brief_path = WORKSPACE / "tasks" / "news_analysis.md"

if not brief_path.exists():
    print(f"❌ Brief not found: {brief_path}")
    sys.exit(1)

# ── Read brief ──────────────────────────────────────────────────────

text = brief_path.read_text(encoding="utf-8")
date_str = datetime.now(timezone.utc).strftime("%B %d, %Y")

# Extract BLUF for subject line
bluf_line = ""
for line in text.split("\n"):
    if line.startswith("## BLUF"):
        bluf_line = line.replace("## BLUF", "").strip()
        break

subject = f"GSIB Daily Brief — {date_str}"

# ── Build email body ────────────────────────────────────────────────

# Convert markdown to Buttondown-compatible HTML (basic conversion)
body_html = f"""<h1>Daily OSINT Intelligence Brief</h1>
<p><em>Published {date_str} by Trevor — automated AI analyst</em></p>
<hr>
{text.replace(chr(10), '<br>')}
<hr>
<p><em>This briefing was automatically generated by Trevor, an AI threat research and evaluation virtual operations resource. Calibrated judgments use Sherman Kent probability bands. Sources scored using NATO Admiralty Code.</em></p>
<p><strong>Subscribe:</strong> <a href="https://quiet-kangaroo-c0b94c.netlify.app">quiet-kangaroo-c0b94c.netlify.app</a></p>
"""

# ── Publish ─────────────────────────────────────────────────────────

api_key = os.environ.get("BUTTONDOWN_API_KEY", "")
if not api_key:
    print("❌ BUTTONDOWN_API_KEY not set")
    sys.exit(1)

payload = {
    "subject": subject,
    "body": body_html,
    "newsletter": NEWSLETTER_ID,
    "status": "draft" if dry_run else "about_to_send",
}

if dry_run:
    print(f"📝 DRY RUN — would post to Buttondown:")
    print(f"   Subject: {subject}")
    print(f"   Body: {len(body_html)} chars")
    print(f"   Status: about_to_send")
    sys.exit(0)

print(f"📬 Publishing to Buttondown...")
print(f"   Subject: {subject}")

request = Request(
    API_URL,
    data=json.dumps(payload).encode(),
    headers={
        "Authorization": f"Token {api_key}",
        "Content-Type": "application/json",
    },
)

try:
    with urlopen(request, timeout=30) as resp:
        result = json.loads(resp.read().decode())
        email_id = result.get("id", "?")
        status = result.get("status", "?")
        print(f"✅ Published! ID: {email_id} | Status: {status}")
except URLError as e:
    print(f"❌ Failed: {e}")
    if hasattr(e, 'read'):
        print(f"   Response: {e.read().decode()[:200]}")
    sys.exit(1)
