#!/usr/bin/env python3
"""
Send the daily GSIB brief via Buttondown newsletter API.
Reads analysis markdown and publishes as a newsletter email.

Usage:
  python3 buttondown-send.py [--subject "Subject"] [--analysis path/to/analysis.md]

Environment:
  BUTTONDOWN_API_KEY - Buttondown API token
"""

import os
import sys
import json
import re
import html as h
import urllib.request
from datetime import datetime, timezone
from pathlib import Path


def parse_args():
    import argparse
    parser = argparse.ArgumentParser(description="Send GSIB brief via Buttondown")
    parser.add_argument("--subject", default="", help="Email subject line")
    parser.add_argument("--analysis", default="", help="Path to analysis markdown file")
    return parser.parse_args()


def build_body(analysis_path: str, date_pt: str) -> str:
    """Convert analysis markdown to Buttondown-friendly HTML."""
    md = Path(analysis_path).read_text()
    lines = md.split("\n")
    
    html_parts = ["<!-- buttondown-editor-mode: fancy -->"]
    html_parts.append("<h1>Global Security &amp; Intelligence Brief</h1>")
    html_parts.append(f"<p><em>Published {date_pt} by Trevor — automated AI analyst</em></p>")
    html_parts.append("<hr>")
    
    for line in lines:
        stripped = line.strip()
        
        # Skip image references, mermaid blocks, code fences, table rows, mermaid graph defs
        if (stripped.startswith("![") or stripped.startswith("```") or 
            stripped.startswith("graph ") or stripped.startswith("    ")):
            continue
        
        # Headers
        if stripped.startswith("## "):
            html_parts.append(f"<h2>{h.escape(stripped[3:])}</h2>")
        elif stripped.startswith("### "):
            html_parts.append(f"<h3>{h.escape(stripped[4:])}</h3>")
        elif stripped.startswith("#### "):
            html_parts.append(f"<h4>{h.escape(stripped[5:])}</h4>")
        # Horizontal rules
        elif stripped.startswith("---") or stripped.startswith("___"):
            html_parts.append("<hr>")
        # Ordered lists
        elif re.match(r"^\d+\.\s+", stripped):
            content = re.sub(r"^\d+\.\s+", "", stripped)
            html_parts.append(f"<li>{h.escape(content)}</li>")
        # Unordered lists
        elif stripped.startswith("- ") or stripped.startswith("* "):
            content = stripped[2:]
            html_parts.append(f"<li>{h.escape(content)}</li>")
        # Bold lines (e.g., BLUF)
        elif stripped.startswith("**") and stripped.endswith("**"):
            html_parts.append(f"<p><strong>{h.escape(stripped[2:-2])}</strong></p>")
        # Table rows - skip for email readability
        elif "|" in stripped and stripped.count("|") >= 3:
            continue
        # Regular paragraphs
        elif stripped:
            html_parts.append(f"<p>{h.escape(stripped)}</p>")
    
    # Footer
    html_parts.append("<hr>")
    html_parts.append("<p><em>This briefing was automatically generated by Trevor, an AI threat research and evaluation virtual operations resource.</em></p>")
    html_parts.append('<p><strong>Subscribe for daily delivery:</strong> <a href="https://trevormentis-spec.github.io/trevor-landing-page/">trevormentis-spec.github.io/trevor-landing-page</a></p>')
    
    return "\n".join(html_parts)


def send_buttondown(api_key: str, subject: str, body: str) -> dict:
    """POST to Buttondown API and return the response."""
    payload = json.dumps({
        "subject": subject,
        "body": body,
        "status": "about_to_send",
    }).encode("utf-8")
    
    req = urllib.request.Request(
        "https://api.buttondown.email/v1/emails",
        data=payload,
        headers={
            "Authorization": f"Token {api_key}",
            "Content-Type": "application/json",
        },
        method="POST",
    )
    
    try:
        with urllib.request.urlopen(req, timeout=30) as resp:
            result = json.loads(resp.read())
            return result
    except urllib.error.HTTPError as e:
        err_body = e.read().decode()
        print(f"Buttondown API error (HTTP {e.code}): {err_body}", file=sys.stderr)
        sys.exit(1)
    except Exception as e:
        print(f"Buttondown API error: {e}", file=sys.stderr)
        sys.exit(1)


def main():
    args = parse_args()
    
    # Get date
    date_pt = os.environ.get("DATE_PT", "")
    if not date_pt:
        from zoneinfo import ZoneInfo
        date_pt = datetime.now(ZoneInfo("America/Los_Angeles")).strftime("%Y-%m-%d")
    
    # API key
    api_key = os.environ.get("BUTTONDOWN_API_KEY", "")
    if not api_key:
        print("ERROR: BUTTONDOWN_API_KEY not set", file=sys.stderr)
        sys.exit(1)
    
    # Analysis file
    repo_dir = Path(__file__).resolve().parent.parent
    analysis_path = args.analysis
    if not analysis_path:
        analysis_path = str(repo_dir / "tasks" / "news_analysis.md")
    
    if not os.path.exists(analysis_path):
        print(f"ERROR: Analysis file not found: {analysis_path}", file=sys.stderr)
        sys.exit(1)
    
    # Subject
    subject = args.subject or f"GSIB Daily Brief — {date_pt}"
    
    print(f"Building newsletter body from: {analysis_path}")
    body = build_body(analysis_path, date_pt)
    
    body_len = len(body)
    print(f"Body HTML: {body_len} chars")
    
    if body_len < 100:
        print("ERROR: Body too short — possible markdown parsing issue", file=sys.stderr)
        sys.exit(1)
    
    print(f"Publishing: {subject}")
    result = send_buttondown(api_key, subject, body)
    
    email_id = result.get("id", "unknown")
    status = result.get("status", "unknown")
    print(f"✅ Published to Buttondown! Email ID: {email_id}")
    print(f"Status: {status}")
    print(f"Subject: {subject}")
    
    return result


if __name__ == "__main__":
    main()
