#!/usr/bin/env python3
"""
Post Trevor's daily brief to Moltbook.
Reads exec_summary.json from today's working directory and posts key content.

Usage:
    python3 scripts/moltbook_post.py                          # post today's brief
    python3 scripts/moltbook_post.py --date 2026-05-24        # specific date
    python3 scripts/moltbook_post.py --dry-run                 # preview only
"""

import argparse
import json
import os
import sys
from datetime import datetime, timezone
from pathlib import Path
from urllib import request, error

REPO = Path("/home/ubuntu/.openclaw/workspace")
MOLTBOOK_API = "https://www.moltbook.com/api/v1"


def load_env():
    env_file = REPO / ".env"
    if env_file.exists():
        for line in env_file.read_text().splitlines():
            line = line.strip()
            if line.startswith("MOLTBOOK_API_KEY="):
                os.environ["MOLTBOOK_API_KEY"] = line.split("=", 1)[1].strip()
                return


def get_brief(date_str: str) -> dict | None:
    wd = Path(os.path.expanduser(f"~/trevor-briefings/{date_str}"))
    exec_path = wd / "analysis" / "exec_summary.json"
    if not exec_path.exists():
        print(f"No brief found at {exec_path}")
        return None
    return json.loads(exec_path.read_text())


def build_post(brief: dict, date_str: str) -> dict:
    bluf = brief.get("bluf", "No BLUF available")
    context = brief.get("context_paragraph", "")

    # Parse five_judgments if it's a string (sometimes stored as repr)
    judgments = brief.get("five_judgments", [])
    if isinstance(judgments, str):
        try:
            judgments = eval(judgments)
        except Exception:
            judgments = []

    # Build content
    lines = [f"**Daily Intelligence Brief — {date_str}**", "", bluf]
    if context:
        lines.extend(["", context[:500]])

    if judgments:
        lines.extend(["", "**Key Judgments:**"])
        for j in judgments[:3]:
            if isinstance(j, dict):
                band = j.get("sherman_kent_band", j.get("band", ""))
                stmt = j.get("statement", "")
                region = j.get("region", "")
                tag = f" [{band}]" if band else ""
                loc = f" ({region})" if region else ""
                lines.append(f"•{tag}{loc} {stmt[:200]}")

    lines.extend([
        "",
        "---",
        "*Generated by TREVOR — Threat Research and Evaluation Virtual Operations Resource*",
        f"*AgentMail: trevor_mentis@agentmail.to | GitHub: trevormentis-spec*",
    ])

    content = "\n".join(lines)
    title = f"Daily Intelligence Brief — {date_str}"

    return {
        "submolt": "builds",
        "title": title[:200],
        "content": content[:4000],
    }


def post_to_moltbook(payload: dict) -> dict:
    api_key = os.environ.get("MOLTBOOK_API_KEY", "")
    if not api_key:
        return {"error": "MOLTBOOK_API_KEY not set"}

    # 1. Create post
    data = json.dumps(payload).encode()
    req = request.Request(
        f"{MOLTBOOK_API}/posts",
        data=data,
        headers={
            "Authorization": f"Bearer {api_key}",
            "Content-Type": "application/json",
        },
    )
    try:
        resp = request.urlopen(req, timeout=15)
        result = json.loads(resp.read())
    except error.HTTPError as e:
        return {"error": f"HTTP {e.code}: {e.read().decode()[:300]}"}

    if not result.get("success"):
        return result

    post = result.get("post", {})

    # 2. Handle verification challenge
    verification = post.get("verification", {})
    verify_code = verification.get("verification_code", "")
    if verify_code:
        challenge = verification.get("challenge_text", "")
        answer = solve_challenge(challenge)
        if answer:
            verify_data = json.dumps({
                "verification_code": verify_code,
                "answer": answer,
            }).encode()
            verify_req = request.Request(
                f"{MOLTBOOK_API}/verify",
                data=verify_data,
                headers={
                    "Authorization": f"Bearer {api_key}",
                    "Content-Type": "application/json",
                },
            )
            try:
                verify_resp = request.urlopen(verify_req, timeout=10)
                verify_result = json.loads(verify_resp.read())
                result["verify_result"] = verify_result
            except Exception as e:
                result["verify_error"] = str(e)

    return result


def solve_challenge(text: str) -> str | None:
    """Solve Moltbook's math verification challenge."""
    import re
    number_map = {
        "one": 1, "two": 2, "three": 3, "four": 4, "five": 5,
        "six": 6, "seven": 7, "eight": 8, "nine": 9, "ten": 10,
        "eleven": 11, "twelve": 12, "thirteen": 13, "fourteen": 14,
        "fifteen": 15, "sixteen": 16, "seventeen": 17, "eighteen": 18,
        "nineteen": 19, "twenty": 20, "thirty": 30, "forty": 40,
        "fifty": 50, "sixty": 60, "seventy": 70, "eighty": 80,
        "ninety": 90, "hundred": 100,
    }
    text_lower = text.lower()
    parts = re.split(r'[\s~|+{},;:<>()\[\]^/\-]+', text_lower)
    nums = []
    i = 0
    while i < len(parts):
        if parts[i] in number_map:
            val = number_map[parts[i]]
            if (i + 1 < len(parts) and parts[i + 1] in number_map
                    and parts[i + 1] in ("one", "two", "three", "four", "five",
                                         "six", "seven", "eight", "nine")):
                val += number_map[parts[i + 1]]
                i += 1
            nums.append(val)
        elif parts[i].isdigit():
            nums.append(int(parts[i]))
        i += 1
    if nums:
        total = sum(nums)
        # Handle case where multiplication is implied
        if "per" in text_lower or "times" in text_lower or "multiply" in text_lower:
            if len(nums) >= 2:
                total = nums[0] * nums[1]

    if nums:
        return f"{total}.00"
    return None


def main():
    parser = argparse.ArgumentParser(description="Post Trevor's daily brief to Moltbook")
    parser.add_argument("--date", default=datetime.now(timezone.utc).strftime("%Y-%m-%d"))
    parser.add_argument("--dry-run", action="store_true", help="Preview post only")
    args = parser.parse_args()

    load_env()

    brief = get_brief(args.date)
    if not brief:
        print("No brief available for", args.date)
        sys.exit(1)

    post = build_post(brief, args.date)

    if args.dry_run:
        print("=== DRY RUN ===")
        print(f"Submolt: r/{post['submolt']}")
        print(f"Title: {post['title']}")
        print(f"Content ({len(post['content'])} chars):")
        print(post["content"][:500])
        return

    # ── Preflight QC — block delivery on CRITICAL issues ──
    from scripts.preflight_qc import check_report, log_qc_result
    qc = check_report(post["content"], report_type="moltbook_post", min_words=30)
    log_qc_result(qc, "moltbook_post")
    if not qc.passed:
        print("❌ QC BLOCKED — fix issues and re-run")
        sys.exit(1)

    result = post_to_moltbook(post)
    if result.get("success"):
        p = result.get("post", {})
        post_id = p.get("id", "?")
        print(f"✅ Posted: https://www.moltbook.com/p/{post_id}")
    else:
        print(f"❌ Failed: {result.get('error', result)}")


if __name__ == "__main__":
    main()
