#!/usr/bin/env bash
#==============================================================================
# qc-watchdog.sh — Post-delivery Opus QC + autonomous fix trigger
#
# Fires after daily brief delivery. Runs Opus 4.7 QC on the brief.
# WARN or better → logs and exits silently.
# FAIL or CRITICAL → writes alert to tasks/qc-alert.md for autonomous fix cycle.
#
# Schedule: 5 minutes after brief delivery (cron at 13:05 UTC / 06:05 PT)
#==============================================================================
set -uo pipefail

REPO="/home/ubuntu/.openclaw/workspace"
DATE_UTC=$(date -u +%Y-%m-%d)
LOG="$REPO/logs/qc-watchdog-${DATE_UTC}.log"
ALERT_FILE="$REPO/tasks/qc-alert.md"
WORKING_DIR="$HOME/trevor-briefings/${DATE_UTC}"

source "$REPO/.env" 2>/dev/null || true
export OPENROUTER_API_KEY="${OPENROUTER_API_KEY:-}"
cd "$REPO"

echo "=== QC Watchdog ${DATE_UTC} ===" | tee -a "$LOG"
echo "Started at $(date -u)" | tee -a "$LOG"

# Check if today's brief exists
if [ ! -f "$WORKING_DIR/analysis/exec_summary.json" ]; then
    echo "No brief found for today — skipping QC" | tee -a "$LOG"
    exit 0
fi

# Run Opus QC (separate stderr to avoid JSON parse corruption)
echo "Running Opus QC..." | tee -a "$LOG"
QC_OUTPUT=$(python3 "$REPO/scripts/opus_qc_review.py" \
    --brief-dir "$WORKING_DIR" \
    --json 2>>"$LOG")
QC_RC=$?

OVERALL=$(echo "$QC_OUTPUT" | python3 -c "
import sys, json
try:
    r = json.load(sys.stdin)
    print(r.get('overall', 'UNKNOWN'))
except:
    print('PARSE_ERROR')
" 2>/dev/null || echo "PARSE_ERROR")

echo "QC overall: $OVERALL" | tee -a "$LOG"

# Decision logic
if [ "$OVERALL" = "FAIL" ] || [ "$OVERALL" = "CRITICAL" ]; then
    echo "ALERT: Brief QC returned $OVERALL — triggering autonomous fix cycle" | tee -a "$LOG"

    cat > "$ALERT_FILE" << EOF
# QC Alert — ${DATE_UTC} — ${OVERALL}

**Timestamp:** $(date -u)
**Brief:** ${WORKING_DIR}
**QC Output:**
\`\`\`json
$(echo "$QC_OUTPUT" | python3 -c "import sys,json; r=json.load(sys.stdin); print(json.dumps(r, indent=2))" 2>/dev/null || echo "$QC_OUTPUT")
\`\`\`

## Required Actions
- [ ] Diagnose root cause of ${OVERALL}
- [ ] Apply fixes within autonomy boundaries
- [ ] Re-run pipeline if structural fix applied
- [ ] Surface to principal if fix is architectural or uncertain
- [ ] Update MEMORY.md with lesson learned

---
Auto-generated by qc-watchdog.sh at $(date -u)
EOF

    echo "Alert written to $ALERT_FILE" | tee -a "$LOG"
    exit 1  # Non-zero to signal alert condition
else
    echo "QC ${OVERALL} — no action required" | tee -a "$LOG"
fi

echo "=== QC Watchdog complete ===" | tee -a "$LOG"
exit 0
