"""Send the full TREVOR assessment PDF via Maton Gmail API."""
import base64, json, urllib.request, os

api_key = os.environ["MATON_API_KEY"]
pdf_path = "/home/ubuntu/.openclaw/workspace/exports/pdfs/full-assessment-2026-05-01.pdf"

with open(pdf_path, "rb") as f:
    pdf_data = f.read()

pdf_b64 = base64.b64encode(pdf_data).decode()
boundary = "==TREVOR_BOUNDARY_001"

email_body = f"""From: trevor.mentis@gmail.com
To: Roderick.jones@gmail.com
Subject: TREVOR Intelligence Assessment — Full Report | 1 May 2026
MIME-Version: 1.0
Content-Type: multipart/mixed; boundary="{boundary}"

--{boundary}
Content-Type: text/html; charset="UTF-8"

<html>
<body style="font-family: Arial, sans-serif; max-width: 600px; padding: 20px;">
<h2 style="color: #1a1a2e;">TREVOR Intelligence Assessment</h2>
<p style="color: #666; font-size: 12px;">1 May 2026 | CONFIDENTIAL — CLIENT USE ONLY</p>
<hr>

<p><strong>Assessment completed.</strong> Full 16-section TREVOR v2 methodology report attached.</p>

<h3>Contents:</h3>
<ul>
<li>BLUF / Flash Alert</li>
<li>7 Key Judgments with Sherman Kent calibrated probabilities</li>
<li>PMESII-PT Environmental Scan (all 8 dimensions)</li>
<li>Analysis of Competing Hypotheses (3 hypotheses × 11 evidence items)</li>
<li>4 Scenarios with probability ranges and timelines</li>
<li>Threat Assessment Matrix (8 actors, I×C×O)</li>
<li>Red Team Analysis (IRGC perspective)</li>
<li>15 Indicators & Warnings across escalation, de-escalation, instability tracks</li>
<li>7 Intelligence Gaps with collection requirements</li>
<li>Mandatory Dissenting View</li>
<li>Tiered Recommendations</li>
</ul>

<h3>Diagrams included:</h3>
<ul>
<li>Scenario Decision Tree</li>
<li>Threat Actor Quadrant Chart</li>
<li>Event Timeline</li>
<li>I&W Dashboard</li>
<li>Oil Price Trajectory Chart</li>
</ul>

<p style="color: #666; font-size: 11px; margin-top: 20px;">Generated by DeepSeek V4 Pro using TREVOR v2 methodology with 6 calibration corrections from Iran Campaign Review.</p>
<p style="color: #888; font-size: 10px;">TREVOR Assessment | 1 May 2026 22:45 UTC</p>
</body>
</html>

--{boundary}
Content-Type: application/pdf
Content-Disposition: attachment; filename="TREVOR-Intelligence-Assessment-1-May-2026.pdf"
Content-Transfer-Encoding: base64

{pdf_b64}

--{boundary}--
"""

raw_b64 = base64.urlsafe_b64encode(email_body.encode()).decode()

payload = json.dumps({"raw": raw_b64}).encode()
req = urllib.request.Request(
    "https://gateway.maton.ai/google-mail/gmail/v1/users/me/messages/send",
    data=payload,
    method="POST"
)
req.add_header("Authorization", f"Bearer {api_key}")
req.add_header("Content-Type", "application/json")

try:
    resp = urllib.request.urlopen(req, timeout=60)
    result = json.loads(resp.read())
    msg_id = result.get("id", "unknown")
    print(f"✅ Email sent!")
    print(f"   To: Roderick.jones@gmail.com")
    print(f"   Subject: TREVOR Intelligence Assessment — Full Report | 1 May 2026")
    print(f"   Attachment: TREVOR-Assessment-1-May-2026.pdf (599 KB)")
    print(f"   Message ID: {msg_id}")
except urllib.error.HTTPError as e:
    body = e.read().decode()
    print(f"❌ HTTP {e.code}: {e.reason}")
    print(f"Response: {body[:300]}")
except Exception as e:
    print(f"❌ Error: {e}")
